welcome="欢迎来到Jerry的游戏世界"

background="传说在遥远的纳帕海上有一块神奇的大陆，大陆被五个不同的种族分别统治者，他们是住在东部大陆的人族、住在奇幻大陆的精灵族、住在蒸汽大陆的矮人族、住在西部大陆的巫师部落和住在南部大陆的巨人族，大陆的中部是高耸入云的中部山脉，传说在山脉的最深处封禁着邪恶的黑暗魔神，像所有的神话传说一样，在一次大地震后，黑暗魔神打破了封印，发誓要展开一场血腥的报复......"

# 动作
a1="你一拳打了过去，对方好像毫无还手之力"
a2="你蹲下来，一个扫堂腿，对方迎面摔倒在地"
a3="你使出一招双风灌耳，对方一头栽倒在地"

#